# Generated by Django 4.2 on 2024-12-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='currency_type',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='mileage_type',
            field=models.CharField(choices=[('KM', 'km'), ('MIL', 'mil')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='owner_type',
            field=models.CharField(choices=[('FIRST', 'Birinci'), ('SECOND', 'İkinci'), ('THIRD', 'Üçüncü'), ('OTHER', 'Dördüncü və ya daha çox')], default='s', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='transmission_type',
            field=models.CharField(choices=[('FRONT', 'Ön'), ('REAR', 'Arxa'), ('FULL', 'Tam')], default='s', max_length=10),
        ),
    ]
