# Generated by Django 4.2 on 2024-12-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_announcement_currency_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='currency_type',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='mileage_type',
            field=models.CharField(choices=[('KM', 'km'), ('MIL', 'mil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='number_of_seats',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8+', '8+')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='owner_type',
            field=models.CharField(choices=[('FIRST', 'Birinci'), ('SECOND', 'İkinci'), ('THIRD', 'Üçüncü'), ('OTHER', 'Dördüncü və ya daha çox')], max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='transmission_type',
            field=models.CharField(choices=[('FRONT', 'Ön'), ('REAR', 'Arxa'), ('FULL', 'Tam')], max_length=10),
        ),
    ]
