# Generated by Django 4.2 on 2025-01-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_announcement_currency_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='CarModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='EngineCapacity',
            new_name='engine_capacity',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='ForCountry',
            new_name='for_country',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='FuelType',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='GearBox',
            new_name='gear_box',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='RoofType',
            new_name='roof_type',
        ),
    ]
